version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mlaas"
s3_bucket = "sam-bootstrap-bucket-657dc6ae-0db2-45da-a51b-ce16782bdcc5"
s3_prefix = "mlaas-bootstrap"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
