version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mlaas"
s3_bucket = "sam-bootstrap-bucket-6bb48584-2e9e-4630-a620-ff639d2dbe9e"
s3_prefix = "mlaas-bootstrap"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
